import { Category } from "./category";
import { Post } from "./post"
import { Injectable } from "@angular/core";

@Injectable({
    providedIn: 'root'
  })
export class PostRepository {

    posts:Post[]
    constructor(){
        this.posts = [
            {id:'html',title:'HTML',content:'<p>HTML is the standard markup language for describing the structure of the web pages. Our HTML tutorials will help you to understand the basics of latest HTML5 language, so that you can create your own website.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dapibus erat. Aliquam erat volutpat. Donec ac turpis nibh. Cras at risus varius, imperdiet lectus id, varius orci. Nam sollicitudin vestibulum dui in imperdiet. Vivamus dignissim augue eu diam elementum, nec rutrum arcu tempus. Nunc pharetra malesuada scelerisque. Morbi suscipit sed augue ac viverra. Nullam porta sem et eleifend venenatis. Integer auctor dui lorem, ac commodo tortor dapibus id. Ut convallis eleifend nisi, ut placerat ante ullamcorper ac. Fusce sed orci tempor augue dignissim faucibus. Donec lorem nunc, vulputate eu convallis ut, ornare id ligula. Cras metus nulla, bibendum quis felis a, ornare luctus odio. Phasellus vel tincidunt enim, id pellentesque magna. Cras congue est vel est fringilla, dictum porta enim volutpat.</p>',categories:[{id:'lounge',name:'Lounge'},{id:'frontend',name:'Frontend'}],date:1703312647164,featureImage:{id:'html',url:'https://picsum.photos/600/420?random=1',description:'Feature Image of HTML'}},
            {id:'css',title:'CSS',content:'<p>CSS is used for describing the presentation of web pages. CSS can save a lot of time and effort. Our CSS tutorials will help you to learn the essentials of latest CSS3, so that you can control the style and layout of your website.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dapibus erat. Aliquam erat volutpat. Donec ac turpis nibh. Cras at risus varius, imperdiet lectus id, varius orci. Nam sollicitudin vestibulum dui in imperdiet. Vivamus dignissim augue eu diam elementum, nec rutrum arcu tempus. Nunc pharetra malesuada scelerisque. Morbi suscipit sed augue ac viverra. Nullam porta sem et eleifend venenatis. Integer auctor dui lorem, ac commodo tortor dapibus id. Ut convallis eleifend nisi, ut placerat ante ullamcorper ac. Fusce sed orci tempor augue dignissim faucibus. Donec lorem nunc, vulputate eu convallis ut, ornare id ligula. Cras metus nulla, bibendum quis felis a, ornare luctus odio. Phasellus vel tincidunt enim, id pellentesque magna. Cras congue est vel est fringilla, dictum porta enim volutpat.</p>',categories:[{id:'lounge',name:'Lounge'},{id:'frontend',name:'Frontend'}],date:1691312747164,featureImage:{id:'css',url:'https://picsum.photos/600/420?random=2',description:'Feature Image of CSS'}},
            {id:'javascript',title:'JavaScript',content:'<p>JavaScript is the most popular and widely used client-side scripting language. Our JavaScript tutorials will provide in-depth knowledge of the JavaScript including ES6 features, so that you can create interactive websites.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dapibus erat. Aliquam erat volutpat. Donec ac turpis nibh. Cras at risus varius, imperdiet lectus id, varius orci. Nam sollicitudin vestibulum dui in imperdiet. Vivamus dignissim augue eu diam elementum, nec rutrum arcu tempus. Nunc pharetra malesuada scelerisque. Morbi suscipit sed augue ac viverra. Nullam porta sem et eleifend venenatis. Integer auctor dui lorem, ac commodo tortor dapibus id. Ut convallis eleifend nisi, ut placerat ante ullamcorper ac. Fusce sed orci tempor augue dignissim faucibus. Donec lorem nunc, vulputate eu convallis ut, ornare id ligula. Cras metus nulla, bibendum quis felis a, ornare luctus odio. Phasellus vel tincidunt enim, id pellentesque magna. Cras congue est vel est fringilla, dictum porta enim volutpat.</p>',categories:[{id:'lounge',name:'Lounge'},{id:'frontend',name:'Frontend'}],date:1701312747264,featureImage:{id:'javascript',url:'https://picsum.photos/600/420?random=3',description:'Feature Image of JavaScript'}},
            {id:'bootstrap',title:'Bootstrap',content:'<p>Bootstrap is a powerful front-end framework for faster and easier web development. Our Bootstrap tutorials will help you to learn all the features of latest Bootstrap 4 framework so that you can easily create responsive websites.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dapibus erat. Aliquam erat volutpat. Donec ac turpis nibh. Cras at risus varius, imperdiet lectus id, varius orci. Nam sollicitudin vestibulum dui in imperdiet. Vivamus dignissim augue eu diam elementum, nec rutrum arcu tempus. Nunc pharetra malesuada scelerisque. Morbi suscipit sed augue ac viverra. Nullam porta sem et eleifend venenatis. Integer auctor dui lorem, ac commodo tortor dapibus id. Ut convallis eleifend nisi, ut placerat ante ullamcorper ac. Fusce sed orci tempor augue dignissim faucibus. Donec lorem nunc, vulputate eu convallis ut, ornare id ligula. Cras metus nulla, bibendum quis felis a, ornare luctus odio. Phasellus vel tincidunt enim, id pellentesque magna. Cras congue est vel est fringilla, dictum porta enim volutpat.</p>',categories:[{id:'framework',name:'FrameWork'},{id:'frontend',name:'Frontend'}],date:1700412747164,featureImage:{id:'bootstrap',url:'https://picsum.photos/600/420?random=4',description:'Feature Image of Bootstrap'}},
            {id:'sql',title:'SQL',content:'<p>SQL is a standard language designed for managing data in relational database management system. Our SQL tutorials will help you to learn the fundamentals of the SQL language so that you can efficiently manage your databases.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dapibus erat. Aliquam erat volutpat. Donec ac turpis nibh. Cras at risus varius, imperdiet lectus id, varius orci. Nam sollicitudin vestibulum dui in imperdiet. Vivamus dignissim augue eu diam elementum, nec rutrum arcu tempus. Nunc pharetra malesuada scelerisque. Morbi suscipit sed augue ac viverra. Nullam porta sem et eleifend venenatis. Integer auctor dui lorem, ac commodo tortor dapibus id. Ut convallis eleifend nisi, ut placerat ante ullamcorper ac. Fusce sed orci tempor augue dignissim faucibus. Donec lorem nunc, vulputate eu convallis ut, ornare id ligula. Cras metus nulla, bibendum quis felis a, ornare luctus odio. Phasellus vel tincidunt enim, id pellentesque magna. Cras congue est vel est fringilla, dictum porta enim volutpat.</p>',categories:[{id:'database',name:'DataBase'},{id:'backend',name:'Backend'}],date:1700112747154,featureImage:{id:'sql',url:'https://picsum.photos/600/420?random=5',description:'Feature Image of SQL'}},
            {id:'mongodb',title:'Mongo DB',content:'<p>Mongo DB is a standard language designed for managing data in relational database management system. Our SQL tutorials will help you to learn the fundamentals of the Mongo language so that you can efficiently manage your databases.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eu dapibus erat. Aliquam erat volutpat. Donec ac turpis nibh. Cras at risus varius, imperdiet lectus id, varius orci. Nam sollicitudin vestibulum dui in imperdiet. Vivamus dignissim augue eu diam elementum, nec rutrum arcu tempus. Nunc pharetra malesuada scelerisque. Morbi suscipit sed augue ac viverra. Nullam porta sem et eleifend venenatis. Integer auctor dui lorem, ac commodo tortor dapibus id. Ut convallis eleifend nisi, ut placerat ante ullamcorper ac. Fusce sed orci tempor augue dignissim faucibus. Donec lorem nunc, vulputate eu convallis ut, ornare id ligula. Cras metus nulla, bibendum quis felis a, ornare luctus odio. Phasellus vel tincidunt enim, id pellentesque magna. Cras congue est vel est fringilla, dictum porta enim volutpat.</p>',categories:[{id:'database',name:'DataBase'},{id:'backend',name:'Backend'}],date:1700152747161,featureImage:{id:'mongodb',url:'https://picsum.photos/600/420?random=6',description:'Feature Image of MongoDB'}},]
    }

    getPosts():Post[]{
        return this.posts
    }

    getPostByid(id:string):Post{
        return this.posts.find(u=> u.id==id)!
    }

    getPostsByCategory(cat:string):Post[]{
        return cat=="all" ? this.posts : this.posts.filter(p=> p.categories.find(c=> c.id==cat))!
    }
}
